name: build-on-push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Build debug
        run:  msbuild msvc2022\ui_dxc.sln -t:rebuild -verbosity:quiet -property:Configuration=debug
      - name: Build release
        run:  msbuild msvc2022\ui_dxc.sln -t:rebuild -verbosity:quiet -property:Configuration=release
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1.1.2
        with:
          subject-path: 'bin\**\*.exe'
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui_dxc.release.zip
          path: |
            bin\release\*.exe
          retention-days: 5
      - name: upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui_dxc.debug.zip
          path: |
            bin\debug\*.exe
          retention-days: 5
